# -*- coding: utf-8 -*-
"""Binance_ETHUSDT_1h.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CYlI3-qEM5GT_f9mXgde2dOMO8IAFx8l

### predict the price of ETH
"""

#Import the dependencies
import pandas as pd 
import numpy as np 
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

#load the data
from google.colab import files
files.upload()



df.head(6)

# Get and show the data 
df = pd.read_csv("Binance_ETHUSDT_1h.csv")

df = df.set_index( pd.DatetimeIndex(df['date'].values))
#show data

df.shape

df.info()

projection = 14
df['prediction'] = df[['close']].shift(-projection)

df['prediction']

df.head(5)

df.isna()

X = np.array(df[['close']])
X = X[:-projection]
print(X)

y = df['prediction'].values
y = y[:-projection]
print(y)

#split the data into 80% training and 20% testing data sets

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2 )

linReg = LinearRegression()
#Train the model
linReg.fit(X_train, y_train)

# test the model using score 
linReg_confidence = linReg.score(X_test, y_test)

print(linReg_confidence)

x_projection = np.array(df[['close']])[-projection:]
print(x_projection)

linReg_prediction = linReg.predict(x_projection)
print(linReg_prediction)

